// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetProfileResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

type LoginRequest struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterRequest struct {
	Username        string `json:"username" validate:"required"`
	Password        string `json:"password" validate:"required"`
	ConfirmPassword string `json:"confirmPassword" validate:"required"`
}

type RegisterResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}
